apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: cert-manager
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/eknudtson/certmanager-cd
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: '{{.name}}-cert-manager' # 'name' field of the Secret
    spec:
      project: "cert-manager"
      source:
        repoURL: https://github.com/eknudtson/certmanager-cd
        targetRevision: HEAD
        path: kustomize
      destination:
        server: '{{.server}}' # 'server' field of the secret
        namespace: cert-manager
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
