apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-secrets
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: external-secrets
  destinations:
  - name: in-cluster
    namespace: external-secrets
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/eknudtson/externalsecrets-cd
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: '{{.name}}-external-secrets' # 'name' field of the Secret
    spec:
      project: "external-secrets"
      source:
        repoURL: https://github.com/eknudtson/externalsecrets-cd
        targetRevision: HEAD
        path: kustomize
      destination:
        server: '{{.server}}' # 'server' field of the secret
        namespace: external-secrets
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
